### ISSUE TITLE
argument "x" is missing

### ISSUE THREAD

**Issue by geotheory** [aschinchon/travelling-salesman-portrait#1]
Fails for me:
```
> data.frame(id=solution) %>% 
+   mutate(order=row_number()) -> order
Error in rank(x, ties.method = "first", na.last = "keep") : 
  argument "x" is missing, with no default
```
row_number requires an argument..

**Comment by geotheory** [comment]
Hmm. Re-running code and it works. I must've missed something

**Comment by mthulin** [comment]
This problem occurs because R confuses the mutate function in plyr and dplyr. Replacing mutate with dplyr::mutate as follows fixes it:

```
data.frame(id=solution) %>% 
  dplyr::mutate(order=row_number()) -> order
```

(You'll need to do the same with the other mutate call as well.)

**Comment by geotheory** [comment]
Useful clarification thanks. Neat code btw
